#!/usr/bin/env ruby
#
# Automating the development flow
#
# Assumptions: 
#   git-version-bump available locally
#   deploy_(staging|production) git remote endpoints setup
#   authentication and authorization to staging, production, and github repos

@version_file = ".gvb_version"

def run a, env={}
	puts ">>#{env unless env.empty?} #{a}"
	system(env,a)
	if $?.exitstatus != 0
		puts "!!! I see a failed system call.  #{a} exited state #{$?.exitstatus}"
		exit
	end
end

def deploy env
	branch = git_branch
	run "git checkout -b deploy_temp"
	run "bundle exec rake assets:precompile", { "RAILS_ENV" => env }
	run "git add public/assets"
	run "git commit public/assets -m'compile assets'"
	run "git push deploy_#{env} deploy_temp:master --force"
	run "git checkout #{branch}"
	run "git branch -D deploy_temp"
end

def reset
	run "git branch -D deploy_temp"
end

def gvb_version
	require 'git-version-bump'
	[GVB.major_version, GVB.minor_version, GVB.patch_version]
end

def show_version v=nil
	v ||= gvb_version
	v.join "."
end

def prev_tag 
	`git describe --always`.strip.gsub(/-\d+-g[0-9a-f]+$/, '')
end

def get_diffs
	`git log --format='# %h  %s' #{prev_tag}..HEAD`
end

def up_version x
	m = case x 
		when /^maj?o?r?$/;  [1,"0","0"]
		when /^min?o?r?$/;  [0, 1 ,"0"] 
		when /^pa?t?c?h?$/; [0, 0 , 1 ]
	end
	gvb = gvb_version
	m.each_with_index{|g, i| 
		if g == "0"
			gvb[i] = 0 
		else 
			gvb[i] += g
		end	}
	show_version gvb
end

def write_version v
	File.open(@version_file,"w") {|f| f.write(v)}
end

def git_branch
	`git branch`.split("\n").detect{|a| a.include? "*"}[2..-1]
end

def update_github
	run "git push origin #{git_branch}"
end

def failexit msg
	puts msg
	exit
end

###########################################

if ARGV.empty?
	failexit "push - commands: (push) staging, production; (github) release"
end

@force = true if ARGV.include? "--force"

case ARGV[0]
when "staging" 
	deploy "staging"
when "production"
	deploy "production"
when "reset"
	reset
when "upcoming_version" 
	vb = ARGV[1]
	unless vb
		failexit "I can't tell you the version I'll become unless you give me something to work with"
	end
	v = up_version vb
	puts "If you invoke me with #{vb} I'll go up to version v#{v}"
when "release"
	unless git_branch == "master"
		failexit "Cannot release unless we are on master"
	end

	if `git version-bump show`.include? "dirty"
		failexit "Dirty tree. Cannot release"
	end
	v = up_version ARGV[1]

	if @force	
		puts "Forcing release"
	else
		puts "\nNew version will be #{v}"
		puts "\nDiffs that will be in this new version\n"
		puts get_diffs
		puts "\nYou will be prompted to create release notes if you accept\n"
		print "Are you sure this the right version? (y|scared): "

		STDOUT.flush; resp = STDIN.gets.chomp
		unless resp.downcase() == "y"
			failexit "I'm cancelling that order."
		end
	end

	write_version v
	run "git commit #{@version_file} -m'bump to version #{v}'"
	
	run "git version-bump -n #{ARGV[1]}"
	run "git release"
else 
	puts "I don't understand #{ARGV[0]}"
end


