#!/bin/bash

set -ex

. /usr/local/lib/giddyup/functions.sh

export RACK_ENV="${APP_ENV}"

#share db/${APP_ENV}.sqlite3
#share vendor/bundle

cd "${RELEASE}"

. ./rvmrc

if ! bundle -v >/dev/null; then
	gem install --no-ri --no-rdoc bundler
	hash -d bundle
fi

bundle install --deployment --without development

if [ ${APP_ENV} = 'production' ]; then
	bundle exec rake assets:precompile
fi

sudo allah start machiavelli_unicorn

mv public/system/maintenance.html public/system/maintenance.html.disabled

