#!/bin/bash

set -ex

. /usr/local/lib/giddyup/functions.sh

cd "${RELEASE}"

echo "APP_ENV is ${APP_ENV}"
echo "Linking shared data..."
mkdir -p "vendor/bundle"
share "vendor/bundle"
mkdir -p "config/settings"
share "config/settings/${APP_ENV}.yml"
mkdir -p "lib/extensions"
share "lib/extensions"

echo "Installing gems..."
chruby-exec "$(cat .ruby-version)" -- bundle install --deployment --without 'development test'


if [ ${APP_ENV} = 'production' ]; then
	date
	echo "Precompiling site assets..."
	chruby-exec "$(cat .ruby-version)" -- RAILS_ENV=${APP_ENV} bundle exec rake assets:precompile
fi

sudo allah start machiavelli_${APP_ENV}_unicorn

mv public/system/maintenance.html public/system/maintenance.html.disabled

